apiVersion: v2
name: my-app
description: A learning chart
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - nginx
  - web
home: https://example.com
maintainers:
  - name: Nency
    email: nency@example.com
